# Generated by Django 2.2.1 on 2019-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20190521_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='detail.Hashtag'),
        ),
    ]
